/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -IC:\Users\Owner\.choosenim\toolchains\nim-#devel\lib -o C:\msys32\home\Owner\projects\BN\tests\nimcache\BN_BN.c.o C:\msys32\home\Owner\projects\BN\tests\nimcache\BN_BN.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg;
typedef struct tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA {
  RootObj Sup;
tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* ZERO;
tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* ONE;
tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* TWO;
tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* TEN;
tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* SIXTEEN;
tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* FIFTYEIGHT;
};
struct tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g {
unsigned int single;
unsigned int* digits;
unsigned int alloc;
unsigned int used;
unsigned char sign;
};
struct tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg {
  RootObj Sup;
tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g number;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI32 tyEnum_mp_result_PbABa2o2tImHESo8ptqpNw;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
static N_NIMCALL(void, Marker_tyRef_xlo88LwB2cW2qnu4FtqfEA)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_ohf8wGErqkxj8yO9cDnLWJA)(void* p, NI op);
static N_NIMCALL(void, TM_JIqidB30KBrSNObzOrWn5A_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*, newBN_flLjPg9ahp9bABE2KCs7XKag)(NimStringDesc* numberArg);
N_LIB_PRIVATE N_NIMCALL(void, destroyBN_7v9bcXnuzuOR85ZkjMggEPQ)(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* z);
N_CDECL(void, mp_int_free)(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g* z);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_CDECL(tyEnum_mp_result_PbABa2o2tImHESo8ptqpNw, mp_int_read_string)(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g* x, int base, NCSTRING value);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA* BNNums_w6DBp0ViAscWPZho0p9cSfA;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_JAqfw6YYZm4FsJhuO7CAoA_;
TNimType NTI_AWE9aoSEUfzpVwAyU0DACKg_;
TNimType NTI_WoUxor9aOW0aNnyPoL85T5g_;
extern TNimType NTI_EfDYb5NOiMBijiUDCmXqPw_;
extern TNimType NTI_z69bDkITFbnU1Ow9a3DuPeAg_;
extern TNimType NTI_aai9cIdjrwazYp9aHakMchqw_;
TNimType NTI_xlo88LwB2cW2qnu4FtqfEA_;
TNimType NTI_ohf8wGErqkxj8yO9cDnLWJA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_JIqidB30KBrSNObzOrWn5A_5, "0", 1);
STRING_LITERAL(TM_JIqidB30KBrSNObzOrWn5A_6, "1", 1);
STRING_LITERAL(TM_JIqidB30KBrSNObzOrWn5A_7, "2", 1);
STRING_LITERAL(TM_JIqidB30KBrSNObzOrWn5A_8, "10", 2);
STRING_LITERAL(TM_JIqidB30KBrSNObzOrWn5A_9, "16", 2);
STRING_LITERAL(TM_JIqidB30KBrSNObzOrWn5A_10, "58", 2);
static N_NIMCALL(void, Marker_tyRef_xlo88LwB2cW2qnu4FtqfEA)(void* p, NI op) {
	tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* a;
	a = (tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*)p;
}
static N_NIMCALL(void, Marker_tyRef_ohf8wGErqkxj8yO9cDnLWJA)(void* p, NI op) {
	tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA* a;
	a = (tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA*)p;
	nimGCvisit((void*)(*a).ZERO, op);
	nimGCvisit((void*)(*a).ONE, op);
	nimGCvisit((void*)(*a).TWO, op);
	nimGCvisit((void*)(*a).TEN, op);
	nimGCvisit((void*)(*a).SIXTEEN, op);
	nimGCvisit((void*)(*a).FIFTYEIGHT, op);
}
static N_NIMCALL(void, TM_JIqidB30KBrSNObzOrWn5A_4)(void) {
	nimGCvisit((void*)BNNums_w6DBp0ViAscWPZho0p9cSfA, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, destroyBN_7v9bcXnuzuOR85ZkjMggEPQ)(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* z) {
	nimfr_("destroyBN", "BN.nim");
	nimln_(66, "BN.nim");
	mp_int_free((&(*z).number));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*, newBN_flLjPg9ahp9bABE2KCs7XKag)(NimStringDesc* numberArg) {
	tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* result;
	tyEnum_mp_result_PbABa2o2tImHESo8ptqpNw T1_;
	nimfr_("newBN", "BN.nim");
	result = (tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*)0;
	nimln_(70, "BN.nim");
	result = (tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*) newObj((&NTI_xlo88LwB2cW2qnu4FtqfEA_), sizeof(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg));
	(*result).Sup.m_type = (&NTI_AWE9aoSEUfzpVwAyU0DACKg_);
	nimln_(71, "BN.nim");
	if (!numberArg || (NU)(((NI) 0)) >= (NU)(numberArg->Sup.len)) raiseIndexError();
	T1_ = (tyEnum_mp_result_PbABa2o2tImHESo8ptqpNw)0;
	T1_ = mp_int_read_string((&(*result).number), ((int) 10), ((NCSTRING) ((&numberArg->data[((NI) 0)]))));
	T1_;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU32)((*c).refcount) + (NU32)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU32)(((NI) (ptrdiff_t) (usr))) - (NU32)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		nimln_(185, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln_(218, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(396, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(264, "gc.nim");
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(396, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		nimln_(265, "gc.nim");
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, BN_BNInit000)(void) {
	tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA* T1_;
	nimfr_("BN", "BN.nim");
nimRegisterGlobalMarker(TM_JIqidB30KBrSNObzOrWn5A_4);
	nimln_(77, "BN.nim");
	T1_ = (tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA*)0;
	T1_ = (tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA*) newObj((&NTI_ohf8wGErqkxj8yO9cDnLWJA_), sizeof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA));
	(*T1_).Sup.m_type = (&NTI_JAqfw6YYZm4FsJhuO7CAoA_);
	nimln_(78, "BN.nim");
	asgnRef((void**) (&(*T1_).ZERO), newBN_flLjPg9ahp9bABE2KCs7XKag(((NimStringDesc*) &TM_JIqidB30KBrSNObzOrWn5A_5)));
	nimln_(79, "BN.nim");
	asgnRef((void**) (&(*T1_).ONE), newBN_flLjPg9ahp9bABE2KCs7XKag(((NimStringDesc*) &TM_JIqidB30KBrSNObzOrWn5A_6)));
	nimln_(80, "BN.nim");
	asgnRef((void**) (&(*T1_).TWO), newBN_flLjPg9ahp9bABE2KCs7XKag(((NimStringDesc*) &TM_JIqidB30KBrSNObzOrWn5A_7)));
	nimln_(81, "BN.nim");
	asgnRef((void**) (&(*T1_).TEN), newBN_flLjPg9ahp9bABE2KCs7XKag(((NimStringDesc*) &TM_JIqidB30KBrSNObzOrWn5A_8)));
	nimln_(82, "BN.nim");
	asgnRef((void**) (&(*T1_).SIXTEEN), newBN_flLjPg9ahp9bABE2KCs7XKag(((NimStringDesc*) &TM_JIqidB30KBrSNObzOrWn5A_9)));
	nimln_(83, "BN.nim");
	asgnRef((void**) (&(*T1_).FIFTYEIGHT), newBN_flLjPg9ahp9bABE2KCs7XKag(((NimStringDesc*) &TM_JIqidB30KBrSNObzOrWn5A_10)));
	asgnRef((void**) (&BNNums_w6DBp0ViAscWPZho0p9cSfA), T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, BN_BNDatInit000)(void) {
static TNimNode* TM_JIqidB30KBrSNObzOrWn5A_2[6];
static TNimNode* TM_JIqidB30KBrSNObzOrWn5A_3[5];
static TNimNode TM_JIqidB30KBrSNObzOrWn5A_0[14];
NTI_JAqfw6YYZm4FsJhuO7CAoA_.size = sizeof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA);
NTI_JAqfw6YYZm4FsJhuO7CAoA_.kind = 17;
NTI_JAqfw6YYZm4FsJhuO7CAoA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_JIqidB30KBrSNObzOrWn5A_2[0] = &TM_JIqidB30KBrSNObzOrWn5A_0[1];
NTI_AWE9aoSEUfzpVwAyU0DACKg_.size = sizeof(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg);
NTI_AWE9aoSEUfzpVwAyU0DACKg_.kind = 17;
NTI_AWE9aoSEUfzpVwAyU0DACKg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_AWE9aoSEUfzpVwAyU0DACKg_.flags = 1;
NTI_WoUxor9aOW0aNnyPoL85T5g_.size = sizeof(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g);
NTI_WoUxor9aOW0aNnyPoL85T5g_.kind = 18;
NTI_WoUxor9aOW0aNnyPoL85T5g_.base = 0;
NTI_WoUxor9aOW0aNnyPoL85T5g_.flags = 3;
TM_JIqidB30KBrSNObzOrWn5A_3[0] = &TM_JIqidB30KBrSNObzOrWn5A_0[4];
TM_JIqidB30KBrSNObzOrWn5A_0[4].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[4].offset = offsetof(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g, single);
TM_JIqidB30KBrSNObzOrWn5A_0[4].typ = (&NTI_EfDYb5NOiMBijiUDCmXqPw_);
TM_JIqidB30KBrSNObzOrWn5A_0[4].name = "single";
TM_JIqidB30KBrSNObzOrWn5A_3[1] = &TM_JIqidB30KBrSNObzOrWn5A_0[5];
TM_JIqidB30KBrSNObzOrWn5A_0[5].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[5].offset = offsetof(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g, digits);
TM_JIqidB30KBrSNObzOrWn5A_0[5].typ = (&NTI_z69bDkITFbnU1Ow9a3DuPeAg_);
TM_JIqidB30KBrSNObzOrWn5A_0[5].name = "digits";
TM_JIqidB30KBrSNObzOrWn5A_3[2] = &TM_JIqidB30KBrSNObzOrWn5A_0[6];
TM_JIqidB30KBrSNObzOrWn5A_0[6].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[6].offset = offsetof(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g, alloc);
TM_JIqidB30KBrSNObzOrWn5A_0[6].typ = (&NTI_EfDYb5NOiMBijiUDCmXqPw_);
TM_JIqidB30KBrSNObzOrWn5A_0[6].name = "alloc";
TM_JIqidB30KBrSNObzOrWn5A_3[3] = &TM_JIqidB30KBrSNObzOrWn5A_0[7];
TM_JIqidB30KBrSNObzOrWn5A_0[7].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[7].offset = offsetof(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g, used);
TM_JIqidB30KBrSNObzOrWn5A_0[7].typ = (&NTI_EfDYb5NOiMBijiUDCmXqPw_);
TM_JIqidB30KBrSNObzOrWn5A_0[7].name = "used";
TM_JIqidB30KBrSNObzOrWn5A_3[4] = &TM_JIqidB30KBrSNObzOrWn5A_0[8];
TM_JIqidB30KBrSNObzOrWn5A_0[8].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[8].offset = offsetof(tyObject_mpz_t_WoUxor9aOW0aNnyPoL85T5g, sign);
TM_JIqidB30KBrSNObzOrWn5A_0[8].typ = (&NTI_aai9cIdjrwazYp9aHakMchqw_);
TM_JIqidB30KBrSNObzOrWn5A_0[8].name = "sign";
TM_JIqidB30KBrSNObzOrWn5A_0[3].len = 5; TM_JIqidB30KBrSNObzOrWn5A_0[3].kind = 2; TM_JIqidB30KBrSNObzOrWn5A_0[3].sons = &TM_JIqidB30KBrSNObzOrWn5A_3[0];
NTI_WoUxor9aOW0aNnyPoL85T5g_.node = &TM_JIqidB30KBrSNObzOrWn5A_0[3];
TM_JIqidB30KBrSNObzOrWn5A_0[2].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[2].offset = offsetof(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg, number);
TM_JIqidB30KBrSNObzOrWn5A_0[2].typ = (&NTI_WoUxor9aOW0aNnyPoL85T5g_);
TM_JIqidB30KBrSNObzOrWn5A_0[2].name = "number";
NTI_AWE9aoSEUfzpVwAyU0DACKg_.node = &TM_JIqidB30KBrSNObzOrWn5A_0[2];
NTI_xlo88LwB2cW2qnu4FtqfEA_.size = sizeof(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*);
NTI_xlo88LwB2cW2qnu4FtqfEA_.kind = 22;
NTI_xlo88LwB2cW2qnu4FtqfEA_.base = (&NTI_AWE9aoSEUfzpVwAyU0DACKg_);
NTI_xlo88LwB2cW2qnu4FtqfEA_.marker = Marker_tyRef_xlo88LwB2cW2qnu4FtqfEA;
TM_JIqidB30KBrSNObzOrWn5A_0[1].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[1].offset = offsetof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA, ZERO);
TM_JIqidB30KBrSNObzOrWn5A_0[1].typ = (&NTI_xlo88LwB2cW2qnu4FtqfEA_);
TM_JIqidB30KBrSNObzOrWn5A_0[1].name = "ZERO";
TM_JIqidB30KBrSNObzOrWn5A_2[1] = &TM_JIqidB30KBrSNObzOrWn5A_0[9];
TM_JIqidB30KBrSNObzOrWn5A_0[9].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[9].offset = offsetof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA, ONE);
TM_JIqidB30KBrSNObzOrWn5A_0[9].typ = (&NTI_xlo88LwB2cW2qnu4FtqfEA_);
TM_JIqidB30KBrSNObzOrWn5A_0[9].name = "ONE";
TM_JIqidB30KBrSNObzOrWn5A_2[2] = &TM_JIqidB30KBrSNObzOrWn5A_0[10];
TM_JIqidB30KBrSNObzOrWn5A_0[10].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[10].offset = offsetof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA, TWO);
TM_JIqidB30KBrSNObzOrWn5A_0[10].typ = (&NTI_xlo88LwB2cW2qnu4FtqfEA_);
TM_JIqidB30KBrSNObzOrWn5A_0[10].name = "TWO";
TM_JIqidB30KBrSNObzOrWn5A_2[3] = &TM_JIqidB30KBrSNObzOrWn5A_0[11];
TM_JIqidB30KBrSNObzOrWn5A_0[11].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[11].offset = offsetof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA, TEN);
TM_JIqidB30KBrSNObzOrWn5A_0[11].typ = (&NTI_xlo88LwB2cW2qnu4FtqfEA_);
TM_JIqidB30KBrSNObzOrWn5A_0[11].name = "TEN";
TM_JIqidB30KBrSNObzOrWn5A_2[4] = &TM_JIqidB30KBrSNObzOrWn5A_0[12];
TM_JIqidB30KBrSNObzOrWn5A_0[12].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[12].offset = offsetof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA, SIXTEEN);
TM_JIqidB30KBrSNObzOrWn5A_0[12].typ = (&NTI_xlo88LwB2cW2qnu4FtqfEA_);
TM_JIqidB30KBrSNObzOrWn5A_0[12].name = "SIXTEEN";
TM_JIqidB30KBrSNObzOrWn5A_2[5] = &TM_JIqidB30KBrSNObzOrWn5A_0[13];
TM_JIqidB30KBrSNObzOrWn5A_0[13].kind = 1;
TM_JIqidB30KBrSNObzOrWn5A_0[13].offset = offsetof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA, FIFTYEIGHT);
TM_JIqidB30KBrSNObzOrWn5A_0[13].typ = (&NTI_xlo88LwB2cW2qnu4FtqfEA_);
TM_JIqidB30KBrSNObzOrWn5A_0[13].name = "FIFTYEIGHT";
TM_JIqidB30KBrSNObzOrWn5A_0[0].len = 6; TM_JIqidB30KBrSNObzOrWn5A_0[0].kind = 2; TM_JIqidB30KBrSNObzOrWn5A_0[0].sons = &TM_JIqidB30KBrSNObzOrWn5A_2[0];
NTI_JAqfw6YYZm4FsJhuO7CAoA_.node = &TM_JIqidB30KBrSNObzOrWn5A_0[0];
NTI_ohf8wGErqkxj8yO9cDnLWJA_.size = sizeof(tyObject_BNNumsTypecolonObjectType__JAqfw6YYZm4FsJhuO7CAoA*);
NTI_ohf8wGErqkxj8yO9cDnLWJA_.kind = 22;
NTI_ohf8wGErqkxj8yO9cDnLWJA_.base = (&NTI_JAqfw6YYZm4FsJhuO7CAoA_);
NTI_ohf8wGErqkxj8yO9cDnLWJA_.marker = Marker_tyRef_ohf8wGErqkxj8yO9cDnLWJA;
(&NTI_xlo88LwB2cW2qnu4FtqfEA_)->finalizer = (void*)destroyBN_7v9bcXnuzuOR85ZkjMggEPQ;
}

