/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -IC:\Users\Owner\.choosenim\toolchains\nim-#devel\lib -o C:\msys32\home\Owner\projects\BN\tests\nimcache\BN_leak.c.o C:\msys32\home\Owner\projects\BN\tests\nimcache\BN_leak.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, main_FUO5ue9alTkkUv0oLqONPlw)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*, newBN_flLjPg9ahp9bABE2KCs7XKag)(NimStringDesc* numberArg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parseutilsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parseutilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_bitopsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_bitopsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_mathInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_mathDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_algorithmInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_algorithmDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_unicodeInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_unicodeDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strutilsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strutilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, BN_BNInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, BN_BNDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE N_NIMCALL(void, leakDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_2tVWz3FCulPXbC2VAtQjxA_2, "0", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, main_FUO5ue9alTkkUv0oLqONPlw)(void) {
	nimfr_("main", "leak.nim");
	{
		nimln_(4, "leak.nim");
		while (1) {
			tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg* T3_;
			nimln_(5, "leak.nim");
			T3_ = (tyObject_BNcolonObjectType__AWE9aoSEUfzpVwAyU0DACKg*)0;
			T3_ = newBN_flLjPg9ahp9bABE2KCs7XKag(((NimStringDesc*) &TM_2tVWz3FCulPXbC2VAtQjxA_2));
			T3_;
		}
	}
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_bitopsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_strutilsDatInit000();
	BN_BNDatInit000();
	leakDatInit000();
	stdlib_parseutilsInit000();
	stdlib_bitopsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_unicodeInit000();
	stdlib_strutilsInit000();
	BN_BNInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
	nimfr_("leak", "leak.nim");
	nimln_(7, "leak.nim");
	main_FUO5ue9alTkkUv0oLqONPlw();
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, leakDatInit000)(void) {
}

